[package]
name = "cmakefmt"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
nom = { version = "7.1.3", features = ["alloc"] }
num = { version = "0.4.1", features = [] }
pretty = "0.12.3"
hex = "0.4.3"
bytes = "1.5.0"